public class Main {
    public static void main(String[] args) {
        System.out.println("Task1");
        int n = 4;
        byte b = 12;
        short s = 24;
        long l = 641123345564789123L;
        float f = 2.5F;
        double d = 1.711111111222222;
        System.out.println("Значение переменной а с типом int равно " + n);
        System.out.println("Значение переменной b с типом byte равно " + b);
        System.out.println("Значение переменной s с типом short равно " + s);
        System.out.println("Значение переменной l с типом long равно " + l);
        System.out.println("Значение переменной f с типом float равно " + f);
        System.out.println("Значение переменной d с типом double равно " + d);
        System.out.println();
        System.out.println("Task2");
        double d1 = 2.786;
        long l1 = 987678965549L;
        float f1 = 27.12F;
        int a1 = 569;
        short short0 = -159;
        short short1 = 27897;
        byte b2 = 67;
        System.out.println(d1);
        System.out.println(l1);
        System.out.println(f1);
        System.out.println(a1);
        System.out.println(short0);
        System.out.println(short1);
        System.out.println(b2);
        System.out.println();
        System.out.println("Task3");
        int lP = 23;
        int aS = 27;
        int eA = 30;
        int sum = lP + aS + eA;
        System.out.println("На каждого ученика рассчитано " + 480 / sum + " листов бумаги.");
        System.out.println();
        System.out.println("Task4");
        int bottlesPerMin = 8;
        int bottlesPer20min = bottlesPerMin * 20;
        int bottlesPerDay = bottlesPerMin * 60 * 24;
        int bottlesPer3Day = bottlesPerDay * 3;
        int bottlesPer30Day = bottlesPerDay * 30;
        System.out.println("За 20 минут машина произвела " + bottlesPer20min + " штук бутылок.");
        System.out.println("За день машина произвела " + bottlesPerDay + " штук бутылок.");
        System.out.println("За 3 дня машина произвела " + bottlesPer3Day + " штук бутылок.");
        System.out.println("За 30 дней машина произвела " + bottlesPer30Day + " штук бутылок.");
        System.out.println();
        System.out.println("Task5");
        int whole = 120;
        int white = 2;
        int brown = 4;
        int c = brown + white;
        int classAmount = whole / c;
        int cansPerClassWhite = classAmount * white;
        int cansPerClassBrown = classAmount * brown;
        System.out.println("В школе, где" + classAmount + " классов, нужно" + cansPerClassWhite + " банок белой краски и " + cansPerClassBrown + " банок коричневой краски.");
        System.out.println("Task6");
        int banana = 400;
        int milk = 210;
        int iceCream = 200;
        int eggs = 280;
        int weight = banana + milk + iceCream + eggs;
        float kg = (float) weight / 1000.0F;
        System.out.println("вес спортзавтрака в граммах равен " + weight);
        System.out.println("вес спортзавтрака в килограммах равен " + kg);
        System.out.println();
        System.out.println("Task7");
        double days500PerDay = 14.0;
        double days250PerDay = 28.0;
        double avarage = (days250PerDay + days500PerDay) / 2.0;
        System.out.println("в среднем может понадобиться" + avarage + "дней, если спортсмен сможет терять в весе от 500 до 250 грамм. ");
        System.out.println("Task8");
        int masha = 67760;
        int denis = 83690;
        int kristina = 76230;
        System.out.println();
        double mashaIncrease = (double) masha + (double) masha * 0.1;
        double denisIncrease = (double) denis + (double) denis * 0.1;
        double kristinaIncrease = (double) kristina + (double) kristina * 0.1;
        System.out.println();
        double differanceMasha = mashaIncrease * 12.0 - (double) (masha * 12);
        double differanceDenis = denisIncrease * 12.0 - (double) (denis * 12);
        double differanceKristina = kristinaIncrease * 12.0 - (double) (kristina * 12);
        System.out.println("Маша теперь получает " + mashaIncrease + " рублей. Годовой доход вырос на " + differanceMasha + " рублей.");
        System.out.println("Денис теперь получает " + denisIncrease + " рублей. Годовой доход вырос на " + differanceDenis + " рублей.");
        System.out.println("Денис теперь получает " + kristinaIncrease + " рублей. Годовой доход вырос на " + differanceKristina + " рублей. ");
    }
}
